interface 雨ニモマケズ {
    雨ニモマケズ: string
    風ニモマケズ: string
    雪ニモ夏ノ暑サニモマケヌ: string
    丈夫ナカラダヲモチ: string
    慾ハナク: string
    決シテ瞋ラズ: string
    イツモシヅカニワラッテヰル: string
    一日ニ玄米四合ト: string
    味噌ト少シノ野菜ヲタベ: string
    アラユルコトヲ: string
    ジブンヲカンジョウニ入レズニ: string
    ヨクミキキシワカリ: string
    ソシテワスレズ: string
    野原ノ松ノ林ノ䕃ノ: string
    小サナ萓ブキノ小屋ニヰテ: string
    東ニ病気ノコドモアレバ: string
    行ッテ看病シテヤリ: string
    西ニツカレタ母アレバ: string
    行ッテソノ稲ノ朿ヲ負ヒ: string
    南ニ死ニサウナ人アレバ: string
    行ッテコハガラナクテモイヽトイヒ: string
    北ニケンクヮヤソショウガアレバ: string
    ツマラナイカラヤメロトイヒ: string
    ヒドリノトキハナミダヲナガシ: string
    サムサノナツハオロオロアルキ: string
    ミンナニデクノボートヨバレ: string
    ホメラレモセズ: string
    クニモサレズ: string
    サウイフモノニ: string
    ワタシハナリタイ: string

    南無無辺行菩薩: string
    南無上行菩薩: string
    南無多宝如来: string
    南無妙法蓮華経: string
    南無釈迦牟尼仏: string
    南無浄行菩薩: string
    南無安立行菩薩: string
}
